import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >

        <style>
          {`
          .branded-bg {
            background-image: url('/bg.png');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
          }
          .dark .branded-bg {
            background-image: url('/bg.png');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
          }
        `}
        </style>
        <div className="flex min-h-screen w-full">
          {/* Left 1/3: Form/children */}
          <div className="w-2/5 flex flex-col justify-center items-center bg-white z-10">
            {children}
          </div>
          {/* Right 2/3: Image background */}


          <div className="lg:border lg:border-gray-200 w-3/5  branded-bg flex flex-col ">
            <div className="flex flex-col  lg:p-12 gap-3 mt-52">

              <div className="flex flex-col pl-8 text-white">
                <h1 className="text-7xl ">Welcome To </h1>
                <span className=" text-7xl font-bold " >FESENSI</span>
                <span className="font-semibold mt-5 tracking-[4px]">AI DRIVEN TECH SUPPORT</span>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
